[package]
name = "cddlconv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
cddl = "0.9.1"
clap = { version = "4.3.10", features = ["derive"] }
convert_case = "0.6.0"
